Added plugin template and scripted test
sbt/sbt-maven-plugin pull request #3
Opened 2023-06-15 08:29 UTC by alexmihailov

2023-06-15 09:08 UTC, mkurz commented on build.sbt
> +      scriptedLaunchOpts.value ++ Seq("-Xmx1024M", "-Dplugin.version=" + version.value)
`-Xmx1024M` seems a bit high, I think 256 should be enough. Maybe try 128 first.

2023-06-15 09:09 UTC, mkurz commented
To run the scripted tests with GitHub actions have a look at https://github.com/playframework/playframework/blob/63c8845ca6392094f079c35652a04a12b153d779/.github/workflows/build-test.yml#L145-L178
The most relevant part is: https://github.com/playframework/playframework/blob/63c8845ca6392094f079c35652a04a12b153d779/.github/workflows/build-test.yml#L168-L176

2023-06-15 12:49 UTC, alexmihailov commented on build.sbt
> +      scriptedLaunchOpts.value ++ Seq("-Xmx1024M", "-Dplugin.version=" + version.value)
Hi @mkurz ! Works successfully with 128

2023-06-15 12:49 UTC, alexmihailov commented
> To run the scripted tests with GitHub actions have a look at https://github.com/playframework/playframework/blob/63c8845ca6392094f079c35652a04a12b153d779/.github/workflows/build-test.yml#L145-L178 The most relevant part is: https://github.com/playframework/playframework/blob/63c8845ca6392094f079c35652a04a12b153d779/.github/workflows/build-test.yml#L168-L176

Made a separate job to run scripted test

2023-06-15 14:09 UTC, ihostage approved these changes
LGTM.
I think this is a easiest and understandable first step.
@mkurz WDYT? Can we merge that?

2023-06-15 16:46 UTC, mkurz requested changes
One thing, after that merge ready :wink:

2023-06-16 06:32 UTC, alexmihailov commented on src/sbt-test/sbt-maven/simple/project/build.properties
> +sbt.version=1.9.0
Hi @mkurz ! I fixed this

2023-06-16 09:39 UTC, merged